apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes 
        #Deployment to be created in the Kubernetes cluster
  labels:
    app: react-app
spec:
  replicas: 2 #The number of pods to be created in the 
   #Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec:
      containers:
      - name: react-app #The name of the react.js application container
        #The Docker image for building the React.js application container
        image: xadimousalih/react-app:latest 
        ports:
        - containerPort: 3000 #The port for the React.js application container

      - name: kubectl
        image: lachlanevenson/k8s-kubectl:v1.17.2 # use a version that match 
        command:
          - "/bin/sh"
          - "cat" 
        tty: true

      # - name: kubectl
      #   image: bitnami/kubectl:latest
      #   command:
      #     - "/bin/sh"
      #     - "-c"
      #     - "sleep 99d"
      #   tty: true
      #   securityContext:
      #   runAsUser: 0
      # restartPolicy: Never